Make plugins optional
code4romania/paul-api pull request #64
Opened 2022-08-25 10:31 UTC by danniel

Make the Woocommerce and Mailchimp plugins optional.

They are disabled by default and may be enabled, before building the project, by updating the relevant *env* parameters.

`COMPOSE_PROFILES=with-task-queue` will ask Docker Compose to add Celery and Redis to the build. These two are needed for the plugins.

`PLUGIN_MAILCHIMP_ENABLED=yes` and `PLUGIN_WOOCOMMERCE_ENABLED=yes` will enable the plugins in Django.

By default, with no compose profiles specified, Docker Compose will now only start the API server and the Postgres server.

2022-08-25 13:16 UTC, tudoramariei approved these changes

2022-08-26 15:22 UTC, andreiio requested changes
Hey, thanks for all the work!

Am lăsat câteva comentarii legate de default values pentru plugin-uri și sugestii de cleaning up the docker-compose file.

This PR seems to include și modificările din #63. Can you confirm this is the case și că putem închide celălalt PR?

2022-08-26 15:22 UTC, andreiio commented on deploy/pull.sh
>  docker-compose up -d
I don't think we need this file anymore

2022-08-26 15:22 UTC, andreiio commented on docker-compose.yml
> +      - main
```suggestion
```

2022-08-26 15:22 UTC, andreiio commented on docker-compose.yml
> +      - main
```suggestion
```

2022-08-26 15:22 UTC, andreiio commented on docker-compose.yml
> +      - main
```suggestion
```

2022-08-26 15:22 UTC, andreiio commented on docker-compose.yml
> +      - main
```suggestion
```

2022-08-26 15:22 UTC, andreiio commented on docker-compose.yml
> +      - main
```suggestion
```

2022-08-26 15:22 UTC, andreiio commented on docker-compose.yml
>    main:
```suggestion
```

2022-08-26 15:22 UTC, andreiio commented on .env.example
> +PLUGIN_WOOCOMMERCE_ENABLED=no
Putem să le facem pe astea defaults, în așa fel încât să nu fie nevoie să le setăm explicit?

De preferat în aplicație, dar dacă e complicat, putem merge și pe `ENV` cu default în Dockerfile.

2022-08-31 12:05 UTC, andreiio approved these changes

2022-08-31 12:06 UTC, merged